#!/usr/bin/env python3
"""
============================================================================
TRACE HEADERS - Find all header dependencies for compiled source files
============================================================================

This script traces header file dependencies using multiple methods:
1. Parse .*.cmd files generated during kernel build (most accurate)
2. Use compiler preprocessor (-M flag) as fallback
3. Parse #include directives directly as last resort

Usage:
    ./scripts/bespoke/trace_headers.py <compiled_files.txt> [kernel_dir] [output_file]

Output:
    List of all header files required by the compiled sources
============================================================================
"""

import argparse
import os
import re
import subprocess
import sys
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path
from typing import Set, Optional


def parse_cmd_file(cmd_file: Path) -> Set[str]:
    """
    Parse a .*.cmd file to extract header dependencies.
    These files are generated by the kernel build system and contain
    accurate dependency information.
    """
    headers = set()
    if not cmd_file.exists():
        return headers

    try:
        content = cmd_file.read_text(errors='ignore')
        # Look for deps_* variable which lists all dependencies
        # Format: deps_kernel/sched/core.o := \
        #   include/linux/sched.h \
        #   include/linux/types.h \
        #   ...
        in_deps = False
        for line in content.split('\n'):
            if 'deps_' in line and ':=' in line:
                in_deps = True
                # Extract files from this line
                parts = line.split(':=')
                if len(parts) > 1:
                    files = parts[1].strip().rstrip('\\').split()
                    for f in files:
                        if f.endswith('.h'):
                            headers.add(f.strip())
            elif in_deps:
                if line.strip().endswith('\\'):
                    files = line.strip().rstrip('\\').split()
                else:
                    files = line.strip().split()
                    in_deps = False
                for f in files:
                    if f.endswith('.h'):
                        headers.add(f.strip())
    except Exception:
        pass

    return headers


def parse_dep_file(dep_file: Path) -> Set[str]:
    """
    Parse a .*.d file (Makefile dependency file).
    """
    headers = set()
    if not dep_file.exists():
        return headers

    try:
        content = dep_file.read_text(errors='ignore')
        # Remove line continuations
        content = content.replace('\\\n', ' ')
        # Split on : to get dependencies
        if ':' in content:
            deps_part = content.split(':', 1)[1]
            for token in deps_part.split():
                if token.endswith('.h'):
                    headers.add(token)
    except Exception:
        pass

    return headers


def get_headers_via_compiler(src_file: Path, kernel_dir: Path) -> Set[str]:
    """
    Use compiler preprocessor to get header dependencies.
    This is a fallback method if .cmd files aren't available.
    """
    headers = set()

    # Determine include paths
    include_paths = [
        kernel_dir / "include",
        kernel_dir / "include" / "uapi",
        kernel_dir / "arch" / "x86" / "include",
        kernel_dir / "arch" / "x86" / "include" / "uapi",
        kernel_dir / "arch" / "x86" / "include" / "generated",
        kernel_dir / "arch" / "x86" / "include" / "generated" / "uapi",
        kernel_dir / "include" / "generated",
        kernel_dir / "include" / "generated" / "uapi",
    ]

    # Build compiler command
    cmd = ["gcc", "-M", "-MG", "-nostdinc"]
    for inc in include_paths:
        if inc.exists():
            cmd.extend(["-I", str(inc)])
    cmd.extend([
        "-D__KERNEL__",
        "-D__x86_64__",
        str(src_file)
    ])

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=30,
            cwd=kernel_dir
        )

        # Parse output - format is: target: dep1 dep2 dep3 ...
        output = result.stdout.replace('\\\n', ' ')
        if ':' in output:
            deps_part = output.split(':', 1)[1]
            for token in deps_part.split():
                if token.endswith('.h'):
                    # Normalize path
                    try:
                        p = Path(token)
                        if p.is_absolute():
                            try:
                                headers.add(str(p.relative_to(kernel_dir)))
                            except ValueError:
                                # System header, skip
                                pass
                        else:
                            headers.add(token)
                    except Exception:
                        headers.add(token)
    except Exception:
        pass

    return headers


def scan_includes_directly(src_file: Path, kernel_dir: Path) -> Set[str]:
    """
    Parse #include directives directly from source file.
    Last resort fallback method.
    """
    headers = set()
    include_pattern = re.compile(r'^\s*#\s*include\s*[<"]([^>"]+)[>"]', re.MULTILINE)

    try:
        content = src_file.read_text(errors='ignore')
        for match in include_pattern.finditer(content):
            header = match.group(1)
            # Try to find the actual header file
            for prefix in ["include/", "arch/x86/include/", ""]:
                candidate = kernel_dir / prefix / header
                if candidate.exists():
                    try:
                        headers.add(str(candidate.relative_to(kernel_dir)))
                    except ValueError:
                        headers.add(str(candidate))
                    break
            else:
                # Just record as-is
                headers.add(header)
    except Exception:
        pass

    return headers


def process_source_file(args: tuple) -> Set[str]:
    """Process a single source file and return its header dependencies."""
    src_file_str, kernel_dir_str = args
    src_file = Path(src_file_str)
    kernel_dir = Path(kernel_dir_str)

    headers = set()

    # Convert source path to object path to find .cmd file
    if src_file_str.endswith('.c'):
        obj_path = src_file_str[:-2] + '.o'
    elif src_file_str.endswith('.S'):
        obj_path = src_file_str[:-2] + '.o'
    else:
        return headers

    # Try .cmd file first (most accurate)
    obj_dir = Path(obj_path).parent
    obj_name = Path(obj_path).name
    cmd_file = kernel_dir / obj_dir / f".{obj_name}.cmd"

    headers.update(parse_cmd_file(cmd_file))

    # Try .d file
    dep_file = kernel_dir / (obj_path[:-2] + '.d')
    headers.update(parse_dep_file(dep_file))

    # If we found headers from build files, return them
    if headers:
        return headers

    # Fallback: scan includes directly
    full_src = kernel_dir / src_file
    if full_src.exists():
        headers.update(scan_includes_directly(full_src, kernel_dir))

    return headers


def main():
    parser = argparse.ArgumentParser(
        description='Trace header dependencies for compiled kernel sources'
    )
    parser.add_argument(
        'compiled_files',
        help='File containing list of compiled source files'
    )
    parser.add_argument(
        'kernel_dir',
        nargs='?',
        default='.',
        help='Kernel source directory (default: current directory)'
    )
    parser.add_argument(
        '-o', '--output',
        help='Output file (default: stdout)'
    )
    parser.add_argument(
        '-j', '--jobs',
        type=int,
        default=os.cpu_count(),
        help='Number of parallel jobs'
    )
    parser.add_argument(
        '-v', '--verbose',
        action='store_true',
        help='Verbose output'
    )

    args = parser.parse_args()

    kernel_dir = Path(args.kernel_dir).resolve()
    compiled_list = Path(args.compiled_files)

    if not compiled_list.exists():
        print(f"Error: Compiled files list not found: {compiled_list}", file=sys.stderr)
        sys.exit(1)

    # Read compiled files
    source_files = [
        line.strip()
        for line in compiled_list.read_text().splitlines()
        if line.strip() and not line.startswith('#')
    ]

    if args.verbose:
        print(f"Processing {len(source_files)} source files...", file=sys.stderr)

    # Process files in parallel
    all_headers: Set[str] = set()
    work_items = [(f, str(kernel_dir)) for f in source_files]

    with ProcessPoolExecutor(max_workers=args.jobs) as executor:
        futures = {executor.submit(process_source_file, item): item for item in work_items}

        completed = 0
        for future in as_completed(futures):
            completed += 1
            if args.verbose and completed % 100 == 0:
                print(f"Processed {completed}/{len(source_files)} files...", file=sys.stderr)

            try:
                headers = future.result()
                all_headers.update(headers)
            except Exception as e:
                if args.verbose:
                    src = futures[future][0]
                    print(f"Error processing {src}: {e}", file=sys.stderr)

    # Normalize and filter headers
    normalized_headers = set()
    for h in all_headers:
        # Skip system headers
        if h.startswith('/usr/') or h.startswith('/lib/'):
            continue
        # Skip generated headers that don't exist in source
        if 'generated' in h:
            # These are OK to keep as they're needed
            pass
        normalized_headers.add(h)

    # Sort and output
    sorted_headers = sorted(normalized_headers)

    if args.output:
        with open(args.output, 'w') as f:
            for h in sorted_headers:
                f.write(h + '\n')
        if args.verbose:
            print(f"Wrote {len(sorted_headers)} headers to {args.output}", file=sys.stderr)
    else:
        for h in sorted_headers:
            print(h)

    if args.verbose:
        print(f"Total unique headers found: {len(sorted_headers)}", file=sys.stderr)


if __name__ == "__main__":
    main()
